version: "3.8"
services:
  ktu-bot:
    build: .
    restart: always
    depends_on:
      redis-queue-db:
        condition: service_healthy

  redis-queue-db:
    image: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
