version: "3.8"
services:
  ktu-bot:
    build: .
    restart: always
    depends_on:
      redis-queue:
        condition: service_healthy

  redis-queue:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
